version: 2
jobs:
  build:
    working_directory: ~/django-data-seeder
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo virtualenv venv
            source venv/bin/activate
      - run:
          command: |
            sudo pip install django
            sudo pip install flake8
      - run:
          command: |
            python runtests.py
      - run:
          command: |
            flake8
